= Project Structure & Production Build
:toc:
:toclevels: 4
:icons: font

toc::[]





== Initial steps
1. `webpack.config.prod`
Config for prod environment
2. `/dist` Server
Create `distServer.js` for prod
- Remove webpack.config.dev dependencies
- `app.use(compression());`
- `app.use(express.static('dist'));`
3. In `baseUrljs`, have an option to toggle between API and mockAPI.
Done using `useMockAPI` conditional statement.
Note: `http://localhost:3000/?useMockApi=true` for mockAPI


== build scripts

In `package.json`, following are the build scripts-

    "clean-dist":"rimraf ./dist && mkdir /dist",
    "pre-build":"npm-run-all clea-dist test lint",
    "build":"babel-node buildScripts/build.js",
    "post-build":"babel-node buildScripts/distServer.js"

== Dynamic HTML Generation

Why?

- Reference bundles automatically
- Minify
- Handle dynamic bundle names
- Inject productional resources only.

== Bundle Splitting

Why?

- Speed intial page load
By serving files that are needed
- Avoid re-downloading all libraries
Serve what is required for framework


Usually we used `bundle.js` to bundle all of JS files.

Now, `bundle.js` is splitted to `main.js` and `vendor.js` READ MORE
- `main.js`
JS files served at browser
- `vendor.js`
JS files served and cached.

== Cache Busting
To reduce bandwidth and avoid unnecessary HTTP requests, bust cache.
This provides to bring all builds to a timestamp by hashing the files files so that their name change when content changes. (git revert)

Why?
- Save HTTP Request
- Force request for latest version

How?
1. Handle bundle filename
2. Generate HTML dynamically

Steps
1. Import `webpack-md5-hash` in `webpack.config.prod.js`
2. Add `WebpackMd5Hash()`
3. Add `output.filename: '[name].[chunkhash].js'`

== CSS Bundling
We use [Extract Text Plugin](https://tinyurl.com/yblnff57).

It moves all the required `*.css` modules in entry chunks into a separate CSS file. So your styles are no longer inlined into the JS bundle, but in a separate CSS file `(styles.css)`.

== Error logging

- Raygun
- New Relic
- TrackJS
- Sentry
Considerations

Error Metadata
- Browser
- Strack Trace
- Previous Actiona
- Custom API for enhanced tracking
Notifications and Integration
Analytics and Filtering
Error logging is usually PAID Service.
Here we are using Track.js

Login into Track.js and  check log error

